version: '3.3'

services:

    app:
      build: .
      depends_on: 
        - 'database'
      ports: 
        - '3000:3000'
  
    database:
      build: ./database
      restart: always
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=admin
        - POSTGRES_DB=database

